QTKEYCHAIN_VERSION = 0.13.2
QTKEYCHAIN_SOURCE = qtkeychain-$(QTKEYCHAIN_VERSION).tar.gz
QTKEYCHAIN_SITE = $(call github,frankosterfeld,qtkeychain,v$(QTKEYCHAIN_VERSION))
QTKEYCHAIN_INSTALL_STAGING = YES
QTKEYCHAIN_INSTALL_TARGET = YES
QTKEYCHAIN_LICENSE = ModifiedBSD
QTKEYCHAIN_DEPENDENCIES = qt5base

$(eval $(cmake-package))
